---
- name: Install OpenJDK
  apt:
    name: default-jdk
    update_cache: yes

- name: Create Tomcat user
  user:
    name: tomcat
    system: yes
    create_home: no
    home: /opt/tomcat
    shell: /bin/false

- name: Download tomcat archive
  get_url:
    url: http://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz
    dest: /tmp
    mode: "777"

- name: Extract Tomcat archive
  unarchive:
    src: /tmp/apache-tomcat-9.0.27.tar.gz
    dest: /opt/tomcat

- name: Manage directory ownership
  file:
    path: /opt/tomcat/apache-tomcat-9.0.27
    state: directory
    recurse: yes
    owner: tomcat

- name: Symbolic link creation
  file:
    src: /opt/tomcat/apache-tomcat-9.0.27
    dest: /opt/tomcat/latest
    state: link

- name: Manage scripts permissions
  file:
    path: "{{ item }}"
    mode: a+x
  with_fileglob:
    - "/opt/tomcat/latest/bin/*.sh"

- name: Create systemd unit file
  copy:
    src: "{{ role_path }}/files/tomcat.service"
    dest: /etc/systemd/system/tomcat.service

- name: Notify systemd that new unit file is available
  command: systemctl daemon-reload

- name: Start tomcat service
  command: systemctl start tomcat

- name: Check tomcat service status
  command: systemctl status tomcat

- name: Enable tomcat autostart
  command: systemctl enable tomcat
